"""Render REPORT.md from results/ alone (never reads the summary statistics)."""
from __future__ import annotations

import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "results")


def fnum(row, key, digits=4, signed=True):
    raw = row.get(key, "")
    if raw in ("", None):
        return "--"
    value = float(raw)
    return f"{value:+.{digits}f}" if signed else f"{value:.{digits}f}"


def main():
    with open(os.path.join(RESULTS, "estimates.csv"), newline="") as fh:
        rows = list(csv.DictReader(fh))
    live = sorted((r for r in rows if r["status"] == "ok"),
                  key=lambda r: -float(r["rho_beta"] or 0))

    prov = {}
    path = os.path.join(RESULTS, "provenance.json")
    if os.path.exists(path):
        prov = json.load(open(path))
    any_run = next(iter(prov.get("runs", {}).values()), {})
    packages = any_run.get("packages", {})

    out = []
    w = out.append
    w("# Polygenic overlap when one trait is oligogenic\n")
    w("*Generated by `report.py` from `results/estimates.csv`. Do not edit by "
      "hand.*\n")
    w(f"bipred {packages.get('bipred', '?')}, ldpred3 "
      f"{packages.get('ldpred3', '?')}, numpy {packages.get('numpy', '?')} on "
      f"{any_run.get('platform', '?')}. Arm 001: lenient per-variant QC, "
      f"long-range LD retained, LD-consistency screen on.\n")

    w("## Finding\n")
    w("For lipoprotein(a) against coronary artery disease, genome-wide `rg` is "
      "+0.0481 -- indistinguishable from noise -- and cross-trait LDSC puts it "
      "at -0.0945 (se 0.1161), pointing the wrong way. The same fit estimates "
      "**106 causal variants** for Lp(a) against 1,459 for CAD, 46% of them "
      "shared, with effects correlating **+0.3644**.\n")
    w("Averaging one very large locus over a million variants destroys the "
      "signal. The architecture summary does not average it away.\n")

    w("## rho_beta orders by biological closeness\n")
    w("| pair | rho_beta | frac_shared | rg | LDSC rg |")
    w("|---|---:|---:|---:|---:|")
    for r in live:
        w(f"| {r['pair']} | **{float(r['rho_beta']):+.4f}** | "
          f"{fnum(r, 'frac_shared', 4, False)} | {fnum(r, 'rg')} | "
          f"{fnum(r, 'ldsc_rg')} |")
    w("")
    w("The top of the range is set by two pairs where the answer was known in "
      "advance: direct against total bilirubin (two studies of the same "
      "biology) and urate against gout (crystals are the disease mechanism). "
      "Both land near +0.99. The bottom is set by three pairs with no expected "
      "shared biology, which fall between -0.11 and -0.05. Lp(a) x CAD sits at "
      "+0.3644, with the related pairs rather than with the null.\n")
    w("**`frac_shared` is not the informative statistic.** Unrelated polygenic "
      "pairs still share 63-80% of their causal variants; for polygenic traits "
      "that is the default. The direction correlation is what discriminates.\n")

    w("## All estimates\n")
    w("| pair | m | LDSC rg | rg | frac_shared | rho_beta | n_causal | "
      "n_shared | h2 | cancel | div |")
    w("|---|---:|---:|---:|---:|---:|---|---:|---|---|:-:|")
    for r in rows:
        mark = "" if r["status"] == "ok" else f" _({r['status']})_"
        div = "**yes**" if r.get("divergence_warned") == "1" else "no"
        w(f"| {r['pair']}{mark} | {int(r['m']):,} | {fnum(r, 'ldsc_rg')} | "
          f"{fnum(r, 'rg')} | {fnum(r, 'frac_shared', 4, False)} | "
          f"{fnum(r, 'rho_beta')} | {r['n_causal_1']}/{r['n_causal_2']} | "
          f"{int(r['n_shared']):,} | {fnum(r, 'h2_1', 3, False)}/"
          f"{fnum(r, 'h2_2', 3, False)} | {fnum(r, 'cancel_1', 2, False)}/"
          f"{fnum(r, 'cancel_2', 2, False)} | {div} |")
    w("")

    w("## Caveats\n")
    w("- **`rg` +0.0481 for Lp(a) x CAD is not a null result**, and will be "
      "read as one if quoted without the architecture explanation.\n")
    w("- **Lp(a)'s h2 of 0.007 is a reference limitation.** HapMap3 tags the "
      "LPA KIV-2 repeat poorly; it is not an estimate of Lp(a) heritability.\n")
    w("- **Lp(a) is a 4-cohort meta at 95.9% European** against a European LD "
      "reference. The European-only alternative covered 16% and was unusable.\n")
    w("- **The Sinnott-Armstrong panel publishes no allele frequency**, so the "
      "AF-concordance check is vacuous for those traits and their `af corr` of "
      "+1.0000 is an artifact. See `_lib/datasets.md`.\n")
    w("- **Sample overlap is substantial** -- most exposures are UK Biobank. "
      "The cross-trait intercept absorbs it and is recorded per pair.\n")
    w("- **The overlap statistics carry no interval**, so the null band is "
      "descriptive, not a test. Largest gap in this analysis.\n")
    w("- **One pair was rejected on data grounds**, not results: bilirubin x "
      "gallstones. `_lib/datasets.md` records why.\n")

    with open(os.path.join(HERE, "REPORT.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote REPORT.md ({len(live)} live estimates, {len(rows)} rows)")


if __name__ == "__main__":
    main()
