"""Render REPORT.md from results/ alone.

Deliberately reads nothing but the committed CSV and provenance: if rendering
the report needed the summary statistics, the study would not be readable by
anyone who does not already have 9 GB of GWAS files.
"""
from __future__ import annotations

import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "results")

#: rho_beta tiers, from the anchors and controls declared in config.toml.
TIERS = [(0.90, "same trait / causal mechanism"),
         (0.60, "shared physiology"),
         (0.20, "downstream correlate"),
         (-1.0, "null band")]


def tier(rho):
    for cut, name in TIERS:
        if rho >= cut:
            return name
    return "null band"


def load():
    with open(os.path.join(RESULTS, "estimates.csv"), newline="") as fh:
        return list(csv.DictReader(fh))


def fnum(row, key, digits=4, signed=True):
    raw = row.get(key, "")
    if raw in ("", None):
        return "--"
    value = float(raw)
    return f"{value:+.{digits}f}" if signed else f"{value:.{digits}f}"


def main():
    rows = load()
    live = [r for r in rows if r["status"] == "ok"]
    live.sort(key=lambda r: -float(r["rho_beta"] or 0))

    prov = {}
    path = os.path.join(RESULTS, "provenance.json")
    if os.path.exists(path):
        prov = json.load(open(path))
    any_run = next(iter(prov.get("runs", {}).values()), {})
    packages = any_run.get("packages", {})

    out = []
    w = out.append
    w("# Polygenic overlap when one trait is oligogenic\n")
    w("*Generated by `report.py` from `results/estimates.csv`. Do not edit by "
      "hand.*\n")
    w(f"bipred {packages.get('bipred', '?')}, ldpred3 "
      f"{packages.get('ldpred3', '?')}, numpy {packages.get('numpy', '?')} -- "
      f"{any_run.get('platform', '?')}\n")

    w("## Finding\n")
    w("Genome-wide `rg` and the overlap parameterisation disagree about "
      "oligogenic exposures, and `rg` is the one that is wrong. For "
      "lipoprotein(a) against coronary artery disease, `rg` is +0.0481 -- "
      "indistinguishable from noise, and cross-trait LDSC puts it at "
      "-0.0945 (se 0.1161), pointing the wrong way. The same fit estimates "
      "**106 causal variants** for Lp(a) against 1,459 for CAD, with 46% of "
      "them shared and their effects correlating **+0.3644**.\n")
    w("Averaging one very large locus over a million variants is what destroys "
      "the signal. The architecture summary does not average it away.\n")

    w("## Calibration\n")
    w("`rho_beta` is only interpretable against a scale. The anchors and "
      "controls in `config.toml` supply one, and it comes out monotone in "
      "biological closeness:\n")
    w("| pair | rho_beta | frac_shared | rg | reading |")
    w("|---|---:|---:|---:|---|")
    for r in live:
        rho = float(r["rho_beta"])
        w(f"| {r['pair']} | **{rho:+.4f}** | {fnum(r, 'frac_shared', 4, False)} "
          f"| {fnum(r, 'rg')} | {tier(rho)} |")
    w("")
    w("Two consequences worth stating.\n")
    w("**`frac_shared` is not the informative statistic.** Pairs with no "
      "shared biology still share 63-80% of their causal variants -- for "
      "polygenic traits that is simply the default. What separates related "
      "from unrelated is the direction correlation.\n")
    w("**The null band is roughly -0.11 to -0.05**, measured from the three "
      "declared controls. That is what places Lp(a) x CAD's +0.3644 with the "
      "genuinely related pairs rather than with noise.\n")

    w("## All estimates\n")
    w("| pair | m | LDSC rg | rg | frac_shared | rho_beta | n_causal | "
      "n_shared | h2 | cancel | div |")
    w("|---|---:|---:|---:|---:|---:|---|---:|---|---|:-:|")
    for r in rows:
        mark = "" if r["status"] == "ok" else f" _({r['status']})_"
        div = "**yes**" if r.get("divergence_warned") == "1" else "no"
        w(f"| {r['pair']}{mark} | {int(r['m']):,} | {fnum(r, 'ldsc_rg')} | "
          f"{fnum(r, 'rg')} | {fnum(r, 'frac_shared', 4, False)} | "
          f"{fnum(r, 'rho_beta')} | {r['n_causal_1']}/{r['n_causal_2']} | "
          f"{int(r['n_shared']):,} | {fnum(r, 'h2_1', 3, False)}/"
          f"{fnum(r, 'h2_2', 3, False)} | {fnum(r, 'cancel_1', 2, False)}/"
          f"{fnum(r, 'cancel_2', 2, False)} | {div} |")
    w("")

    w("## Caveats\n")
    w("These bind to the numbers above and should travel with any quotation "
      "of them.\n")
    w("- **`rg` +0.0481 for Lp(a) x CAD is not a null result.** Quoted without "
      "the oligogenicity explanation it will be read as one.\n")
    w("- **Lp(a)'s h2 of 0.007 is a reference limitation.** HapMap3 common "
      "variants tag the LPA KIV-2 repeat poorly; this is not an estimate of "
      "Lp(a) heritability.\n")
    w("- **Lp(a) is a 4-cohort meta at 95.9% European** against a European LD "
      "reference. The European-only alternative covered 16% and was unusable.\n")
    w("- **The Sinnott-Armstrong panel publishes no allele frequency**, so the "
      "AF-concordance check is vacuous for those traits and their `af corr` "
      "of +1.0000 is an artifact. See `_lib/datasets.md`.\n")
    w("- **Sample overlap is substantial** -- most exposures are UK Biobank. "
      "The cross-trait intercept absorbs it and is recorded per pair.\n")
    w("- **One pair was rejected on data grounds**, not results: "
      "bilirubin x gallstones. `_lib/datasets.md` records why.\n")

    text = "\n".join(out) + "\n"
    with open(os.path.join(HERE, "REPORT.md"), "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote REPORT.md ({len(live)} live estimates, {len(rows)} rows)")


if __name__ == "__main__":
    main()
