"""Render REPORT.md from results/ alone (no summary statistics required)."""
from __future__ import annotations

import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, "results")
CANCELLATION_LIMIT = 10.0


def main():
    with open(os.path.join(RESULTS, "estimates.csv"), newline="") as fh:
        rows = list(csv.DictReader(fh))
    prov = {}
    path = os.path.join(RESULTS, "provenance.json")
    if os.path.exists(path):
        prov = json.load(open(path))

    platforms = []
    for r in rows:
        key = (r["platform"], r["bipred"])
        if key not in platforms:
            platforms.append(key)

    out = []
    w = out.append
    w("# LDL x CAD across three levels of QC\n")
    w("*Generated by `report.py` from `results/estimates.csv`. Do not edit by "
      "hand.*\n")

    w("## Estimates\n")
    for platform, version in platforms:
        w(f"**{platform}, bipred {version}**\n")
        w("| stage | m | LDSC rg | bipred rg | h2 LDL | h2 CAD | "
          "cancel LDL | cancel CAD | diverged |")
        w("|---|---:|---:|---:|---:|---:|---:|---:|:-:|")
        for r in rows:
            if (r["platform"], r["bipred"]) != (platform, version):
                continue
            div = "**yes**" if r["divergence_warned"] == "1" else "no"
            w(f"| {r['stage']} | {int(r['m']):,} | {float(r['ldsc_rg']):+.4f} "
              f"| {float(r['rg']):+.4f} | {float(r['h2_ldl']):.4f} "
              f"| {float(r['h2_cad']):.4f} "
              f"| {float(r['cancellation_ldl']):.2f} "
              f"| {float(r['cancellation_cad']):.2f} | {div} |")
        w("")

    w("## Reading\n")
    w(f"The LD-consistency screen is the load-bearing step. Cancellation "
      f"(`sum(beta^2)/h2`) falls from ~271 to ~0.65 and the divergence warning "
      f"clears. Above the limit of {CANCELLATION_LIMIT:.0f} the effects are "
      f"cancelling through LD rather than adding, so the `rg` reported at the "
      f"first two stages is not an estimate of anything.\n")

    if len(platforms) > 1:
        w("## Cross-platform comparison\n")
        by_stage = {}
        for r in rows:
            by_stage.setdefault(r["stage"], []).append(r)
        w("| stage | " + " | ".join(f"{p} ({v})" for p, v in platforms)
          + " | delta |")
        w("|---|" + "---:|" * (len(platforms) + 1))
        for stage, group in by_stage.items():
            vals = []
            for platform, version in platforms:
                match = [g for g in group
                         if (g["platform"], g["bipred"]) == (platform, version)]
                vals.append(float(match[0]["rg"]) if match else None)
            known = [v for v in vals if v is not None]
            delta = f"{max(known) - min(known):+.4f}" if len(known) > 1 else "--"
            w(f"| {stage} | " + " | ".join(
                "--" if v is None else f"{v:+.4f}" for v in vals)
              + f" | {delta} |")
        w("")
        w("Stages 1 and 2 agree to every recorded digit across a different OS, "
          "architecture, BLAS and an independently rebuilt LD reference. Stage "
          "3 differs because bipred 0.3.6 reseeded the screening masks, which "
          "moves 200 of ~845,000 variants. That is a deliberate change, but it "
          "is also a biological estimate shifting under an implementation "
          "refactor -- the reason this lives in `studies/` rather than "
          "`benchmarks/`.\n")

    w("## Provenance\n")
    for tag, run in prov.get("runs", {}).items():
        pkgs = run.get("packages", {})
        w(f"- **{tag}** -- {run.get('platform', '?')}, python "
          f"{run.get('python', '?')}, bipred {pkgs.get('bipred', '?')}, "
          f"ldpred3 {pkgs.get('ldpred3', '?')}, source "
          f"`{str(run.get('source_revision', '?'))[:12]}`")
    w("")
    w("Inputs are not committed; see `../_lib/traits.toml` and "
      "`benchmarks/README.md` Table 4 for acquisition.\n")

    with open(os.path.join(HERE, "REPORT.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote REPORT.md ({len(rows)} rows, {len(platforms)} runs)")


if __name__ == "__main__":
    main()
